package com.example.b07demosummer2024;

/**
 * Model class representing a safe location entry saved by the user.
 * 
 * Instances are stored in Firebase Realtime Database under the user's
 * {@code safeLocations} node. Each entry has a unique key, an address,
 * and optional notes.
 * 
 */
public class SafeLocationInfo {
    /** Firebase-generated unique key for this location. */
    private String id;

    /** Physical address of the safe location. */
    private String address;

    /** Additional notes or description for the location. */
    private String notes;

    /** Required empty constructor for Firebase deserialization. */
    public SafeLocationInfo() { }

    /**
     * Constructs a new SafeLocationInfo with the specified address and notes.
     *
     * @param address Non-null physical address of the location.
     * @param notes   Optional descriptive notes.
     */
    public SafeLocationInfo(String address, String notes) {
        this.address = address;
        this.notes = notes;
    }

    /**
     * Returns the Firebase key of this location.
     *
     * @return Unique identifier, or {@code null} if not yet saved.
     */
    public String getId() { return id; }

    /**
     * Sets the Firebase key for this location.
     *
     * @param id Unique identifier generated by Firebase.
     */
    public void setId(String id) { this.id = id; }

    /**
     * Returns the address of the location.
     *
     * @return Non-null address string.
     */
    public String getAddress() { return address; }
    /**
     * Updates the address of the location.
     *
     * @param address New non-null address.
     */
    public void setAddress(String address) { this.address = address; }

    /**
     * Returns any notes associated with the location.
     *
     * @return Notes string, may be empty or {@code null}.
     */
    public String getNotes() { return notes; }
    /**
     * Updates the notes for the location.
     *
     * @param notes New notes string; may be empty.
     */
    public void setNotes(String notes) { this.notes = notes; }
}
